spring.application.name=ChurchManagementSystemBackend
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=Shaina2316.
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=ThisIsMyVeryLongSecretKeyThatShouldBeAtLeast32CharactersLong123456789
jwt.expiration=86400000

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}